ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS share_level BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS share_streak BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS share_categories BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS share_moments BOOLEAN NOT NULL DEFAULT FALSE;